[project]
name = "lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imageio>=2.37.0",
    "notebook>=7.4.3",
    "pandas>=2.3.0",
    "torch>=2.7.1",
]
